// packages/web/src/lib/specializations.ts
export const SPECIALIZATIONS = [
  "Addiction Medicine",
  "Allergy & Immunology",
  "Anesthesiology",
  "Cardiology",
  "Cardiothoracic Surgery",
  "Critical Care Medicine (Intensive Care)",
  "Dermatology",
  "Emergency Medicine",
  "Endocrinology",
  "Family Medicine",
  "Gastroenterology",
  "General Surgery",
  "Geriatric Medicine",
  "Geriatric Psychiatry",
  "Hematology",
  "Hematology–Oncology",
  "Hospital Medicine",
  "Infectious Disease",
  "Internal Medicine",
  "Medical Genetics / Genomic Medicine",
  "Neonatology",
  "Nephrology",
  "Neurology",
  "Neurosurgery",
  "Nuclear Medicine",
  "Obstetrics & Gynecology (OB/GYN)",
  "Oncology (Medical Oncology)",
  "Ophthalmology",
  "Orthopedic Surgery",
  "Otolaryngology (ENT)",
  "Pathology",
  "Pediatrics",
  "Pediatric Cardiology",
  "Pediatric Endocrinology",
  "Physical Medicine & Rehabilitation (PM&R)",
  "Plastic Surgery",
  "Preventive Medicine",
  "Psychiatry",
  "Pulmonology / Pulmonary & Critical Care",
  "Radiation Oncology",
  "Radiology (Diagnostic Radiology)",
  "Rheumatology",
  "Sleep Medicine",
  "Sports Medicine",
  "Urology",
  "Vascular Surgery",
] as const;
export type Specialization = (typeof SPECIALIZATIONS)[number];
